language: ruby
rvm:
  - '1.9.3'
before_install:
  #install casperjs and phantomjs
  - sudo mkdir /home/travis/bin/
  - wget https://phantomjs.googlecode.com/files/phantomjs-1.9.1-linux-x86_64.tar.bz2
  - tar xjf phantomjs-1.9.1-linux-x86_64.tar.bz2
  - sudo cp phantomjs-1.9.1-linux-x86_64/bin/phantomjs /home/travis/bin/
  - phantomjs --version
  - ls -l /home/travis/bin/
  - git clone git://github.com/n1k0/casperjs.git
  - cd casperjs
  - git checkout tags/1.0.2
  - sudo ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs
  - cd ..
  - casperjs --version
  - python --version
  #install other
  - sudo apt-get install aptitude
  - echo "yes" | sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo aptitude update
  - sudo aptitude -y install libgdal1h=1.10.0-1~precise1 libgeos-dev libgeos++-dev libproj-dev
  - sudo aptitude -y install postgis=2.0.3-2~precise1 postgresql-9.1-postgis-2.0=2.0.3-2~precise1
  - sudo apt-get update
  - aptitude search postgresql
  - sudo apt-get install build-essential chrpath git-core libssl-dev libfontconfig1-dev
  - cp config/database.travisci.yml config/database.yml
  - cp config/social_services.yml.example config/social_services.yml
  - dropdb smorodina_test
  - dropdb smorodina_dev
  - psql -c 'create database smorodina_test;' -U postgres
  - psql -c 'create database smorodina_dev;' -U postgres
  - psql smorodina_test -c 'CREATE EXTENSION hstore; CREATE EXTENSION postgis;' -U postgres
  - psql smorodina_test -f db/sql/pgsnapshot_schema_0.6.sql -U postgres
  - psql smorodina_test -c 'drop table users;' -U postgres
  - psql smorodina_test -f db/sql/agc_generation_functions.sql -U postgres
  - git clone https://github.com/umitanuki/kmeans-postgresql.git
  - cd kmeans-postgresql
  - make
  - sudo cp ./kmeans.so $(pg_config --pkglibdir)
  - sudo cp ./kmeans.control ./kmeans--1.1.0.sql $(pg_config --sharedir)/extension/
  - cd ..
  - psql smorodina_test -f db/sql/kmeans.sql -U postgres
  - sudo aptitude install postgresql-plpython-9.1
  - wget https://www.dropbox.com/s/h462fcazedyhk8m/testdump-16-07-2013.bz2
  - bunzip2 ./testdump-16-07-2013.bz2
  - psql smorodina_dev < testdump-16-07-2013 -U postgres
before_script:
  # - bundle exec rake db:migrate 
  - bundle install
  - rails s
  - casperjs test ./tests/*_test.coffee --url=http://localhost/
#notifications:
#  hipchat: 56de6c6e69b953ec863afab78a4e65@Smorodina dev
