language: ruby
rvm:
  - '1.9.3'
before_install:
  - sudo apt-get install aptitude
  - echo "yes" | sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo aptitude update
  - sudo aptitude -y install libgdal1h=1.10.0-1~precise1 libgeos-dev libgeos++-dev libproj-dev
  - sudo aptitude -y install postgis=2.0.3-2~precise1 postgresql-9.1-postgis-2.0=2.0.3-2~precise1
before_script:
  - cp config/database.travisci.yml config/database.yml
  - cp config/social_services.yml.example config/social_services.yml
  - psql -c 'create database smorodina_test;' -U postgres
  - psql smorodina_test -c 'CREATE EXTENSION hstore; CREATE EXTENSION postgis;' -U postgres
  - psql smorodina_test -f db/sql/pgsnapshot_schema_0.6.sql -U postgres
  - psql smorodina_test -c 'drop table users;' -U postgres
  - psql smorodina_test -f db/sql/agc_generation_functions.sql -U postgres
  - bundle exec rake db:migrate
  - git clone https://github.com/umitanuki/kmeans-postgresql.git
  - cd kmeans-postgresql
  - make
  - sudo cp ./kmeans.so $(pg_config --pkglibdir)
  - sudo cp ./kmeans.control ./kmeans--1.1.0.sql $(pg_config --sharedir)/extension/
  - cd ..
  - psql smorodina_test -f db/sql/kmeans.sql -U postgres
notifications:
  hipchat: 56de6c6e69b953ec863afab78a4e65@Smorodina dev
