---
sightseeing:
  desc: Что посмотреть?
  sub:
    nature:
      desc: Природа
      sub:
        reservoirs: Водохранилища
        waterflows: Водопады
        volcanos: Вулканы и кратеры
        geysers: Гейзеры
        mountains: Горы
        mud wells: Грязевые источники
        reserves: Заповедники
        zoos: Зоопарки
        catacombs: катакомбы
        spring well: ключи
        canyons: Впадины
        glaciers: Ледники
        seas: Моря
        lakes: Озера
        parks: Парки
        caves: Пещеры
        cataracts: Пороги
        rivers: Реки
        streams: ручьи
    culture:
      desc: Культура
      sub:
        museums: Музеи
    religion:
      desc: Религия
      sub:
        temples: Храмы
    entertainment:
      desc: Развлечения
      sub:
        theatres: Театры
    recreation:
      desc: Активный отдых
      sub:
        land:
          desc: На земле
          sub:
            golf: Гольф
        snow:
          desc: На снегу
          sub:
            skating: Катки

