---
:tddium:
  :test_pattern:
    - spec/models/**_spec.rb
    - spec/controllers/**_spec.rb
  :postgresql:
    :version: '9.1'
    :adapter: 'postgis'
    :config:
      postgis_extension: true
      encoding: utf8
      pool: 5
